### ISSUE TITLE
Implement callback for onConnect() / onReconnect() / onDisconnect() events

### ISSUE THREAD

**Issue by jnidzwetzki** [jnidzwetzki/bitfinex-v2-wss-api-java#93]
Implement a callback that is called when a onConnect() / onReconnect() / onDisconnect() event occurs

**Comment by mironbalcerzak** [comment]
Maybe increasing the scope of this ticket to all 3 events of onConnect() / onReconnect() / onDisconnect() would be of a better use?

**Comment by mironbalcerzak** [comment]
Hi Jan.
I've reviewed things that need to be done around this ticket - and it's not as trivial as I thought at the beginning.

To start with - we need to specify what "connect/disconnect/reconnect" means to us because:
(1) we can notify user regarding websocket connect (`@OnOpen`, `@OnClose` of `WebsocketClientEndpoint`)
(2) we can notify user when `connect()` / `reconnect()` / `disconnect()` method of `BitfinexWebsocketClient` has been successfully executed

Both approaches have got pros and cons.
(1) we lose "reconnect" event as we are not working within the context
(2) we lose "disconnect" event in case of "external" termination of connection (network dies, bitfinex kills the connection, etc.etc.)

More things to consider...
- natural choice for ticket's scenario is introducation of 3 new methods in `BitfinexApiCallbackListeners` and creation of convenience methods in `*Managers`.
- multi account scenario - i can safely assume people will reuse their handlers for events, so it would be smart notifying them which client emitted the event (or not? we can force users to )
- coming back to approach (2) - we cannot simply emit events from `SimpleBitfinexApiBroker`, as in case of `PooledBitfinexApiBroker` we will send multiple events which will confuse users.
- multi event spam will occur when we follow approach (1) too.

Is there anything else we should think of?

Coding task seems interesting - I might take over it if you don't mind :)

Cheers,
-- mb

**Comment by jnidzwetzki** [comment]
Hi Miron,

I like both of your solutions. I had already thought about it and came to similar results. 

- By using the `@OnClose` method of the `WebsocketClientEndpoint`, we have a `CloseReason` object which might be useful in the callback. 

- On the other hand, when it comes to the `PooledBitfinexApiBroker` the `SimpleBitfinexApiBroker` object might be useful in the callback. It allows distinguishing which connection of the pool raises the event. In the `WebsocketClientEndpoint` the `SimpleBitfinexApiBroker` is not available. 

What do you think?

Jan

**Comment by mironbalcerzak** [comment]
Hi Jan,
I came up with (3) solution. onConnectionStateChange(StateEnum) in which we can notify user about all events. StateEnum would be:
-- connection init
-- connection ok
-- connection failed
-- authentication success
-- authentication failed
-- reconnection init
-- reconnecting ok
-- reconnection failed
-- disconnection init
-- disconnection ok
-- disconnection by remote 

(naming may change -- it's just an idea)

I understand people might need it for UI updates within their apps. For more in-detail infos (why disconnected by remote, why connection failed etc. they should revert to checking logs)
To keep the implementation "tidy", I would not implement "one-handler-per-one-state" .
I would skip client "distinguishing" as this can be resolved on API user level (user must  provide new handler per every client).
I would just ensure one event is emitted in case of `PooledBitfinexApiBroker`.

I like this approach the most. What are your thoughts?

Kind regards,
-- mb

**Comment by jnidzwetzki** [comment]
Hi Miron,

I like the idea and I will definitely merge that if you do a PR. ;)

Best Regards
   Jan

**Comment by jnidzwetzki** [comment]
Hi Miron,

great code. I have merged it into the master branch.

Best Regards
Jan
